services:
  app:
    build: .
    environment:
      NODE_ENV: production

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
